### PR TITLE
Add missing version metadata

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks for packaging this!

While having a look at getting the new pyppeteer up and running, I found that this package is reporting its version as `0.0.0`, which breaks `pip check`.

This PR fixes that, somewhat bluntly, by rewriting the `setup.py`, as opposed to patching, as it needs to inject information that won't neccessarily be available, and _might_ keep working.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Of note, this does at least work for 7.0.2, as proposed by #4...

**Comment by bollwyvl** [comment]
thoughts, @kiwi0fruit?

**Comment by kiwi0fruit** [comment]
@bollwyvl does this fix that pip on conda is not aware of pyee version (while conda is aware)?

**Comment by kiwi0fruit** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Yeah, you can sort of tell from ci because some of the intermediate pip
files have the correct version (not 0.0.0). But also pip check.

**Comment by kiwi0fruit** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
